apiVersion: v2
appVersion: 23.3.16
description: A Helm chart for Digital.ai Release
name: digitalai-release
version: 23.3.16
kubeVersion: ">= 1.20.0-0 < 1.30.0-0"
sources:
  - https://github.com/xebialabs/xl-release-kubernetes-helm-chart
  - https://github.com/xebialabs/xl-release
home: https://github.com/xebialabs/xl-release-kubernetes-helm-chart
keywords:
  - Digital.ai
  - Release
  - DAI
  - DAIR
  - Xebia
  - XLR
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
  - name: haproxy-ingress
    version: 0.14.5
    repository: "https://haproxy-ingress.github.io/charts"
    condition: haproxy-ingress.install
  - name: nginx-ingress-controller
    version: 9.9.2
    repository: "https://charts.bitnami.com/bitnami"
    condition: nginx-ingress-controller.install
  - name: postgresql
    version: 12.8.5
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.install
  - name: rabbitmq
    version: 12.0.13
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.install
