apiVersion: v2
appVersion: v23.1
description: A Helm chart for XL Release
name: digitalai-release-ocp
version: "23.1"

dependencies:

- name: postgresql
  version: 10.12.8
  repository: "https://raw.githubusercontent.com/bitnami/charts/c343a91d23e0a90ac783b37a2d51946b74a532f0/bitnami"
  condition: postgresql.install

- name: rabbitmq
  version: 8.26.1
  repository: "https://raw.githubusercontent.com/bitnami/charts/c343a91d23e0a90ac783b37a2d51946b74a532f0/bitnami"
  condition: rabbitmq.install

- name: keycloak
  version: 17.0.1
  repository: "https://codecentric.github.io/helm-charts"
  condition: keycloak.install
