apiVersion: v2
appVersion: v10.3
description: A Helm chart for XL Release
name: digitalai-release-ocp
version: 10.3

dependencies:

- name: postgresql
  version: 10.12.8
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.install

- name: rabbitmq
  version: 8.26.1
  repository: "https://charts.bitnami.com/bitnami"
  condition: rabbitmq.install

- name: keycloak
  version: 15.1.0
  repository: "https://codecentric.github.io/helm-charts"
  condition: keycloak.install
