dependencyManagement {
    versions {
        deployCliVersion="25.1.12-531.800"
        xlDeployTrialVersion="25.1.12-531.800"
        xlReleaseTrialVersion="22.2.0-314.113"
        xlReleaseVersion="25.1.12-531.800"
        xlCliVersion="25.1.12-610.407"
    }
}
