dependencyManagement {
    versions {
        deployCliVersion="27.1.0-beta.827"
        xlDeployTrialVersion="27.1.0-beta.827"
        xlReleaseTrialVersion="22.2.0-314.113"
        xlReleaseVersion="27.1.0-beta.827"
        xlCliVersion="27.1.0-beta.825"
    }
}
