dependencyManagement {
    versions {
        deployCliVersion="26.1.1-407.1214"
        xlDeployTrialVersion="26.1.1-407.1214"
        xlReleaseTrialVersion="22.2.0-314.113"
        xlReleaseVersion="26.1.2-426.130"
        xlCliVersion="26.1.1-421.1356"
    }
}
