apiVersion: operators.coreos.com/v1alpha1
## https://olm.operatorframework.io/docs/concepts/crds/clusterserviceversion/
## https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md
## https://docs.openshift.com/container-platform/4.15/operators/operator_sdk/osdk-generating-csvs.html
## https://access.redhat.com/documentation/zh-cn/openshift_container_platform/4.5/html/operators/osdk-generating-csvs#doc-wrapper
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples-metadata: >-
      {
        "digitalairelease-minimal": {
          "description": "Minimal configuration for the Digital.ai Release operator with embedded Postgresql and RabbitMQ and route setup"
        },
        "digitalairelease-placeholders": {
          "description": "Configuration for the Digital.ai Release operator with placeholders to set. Set at least mandatory placeholders, others that are not set delete"
        },
        "digitalairelease-sample": {
          "description": "Sample configuration with all default values"
        },
      }
    alm-examples: '[]'
    capabilities: Basic Install
    categories: "Integration & Delivery"
    description: Digital.ai Release empowers developer teams to seamlessly release and deploy software on a large scale across hybrid environments, all while ensuring that compliance and security requirements are effectively in place.
    containerImage: "${CONTAINER_IMAGE}"
    createdAt: "${CURRENT_TIME}"
    support: "Digital.ai"
    repository: "https://github.com/digital-ai/release-helm-chart"
  name: digitalai-release-operator.v${VERSION}
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: |-
      Digital.ai Release empowers developer teams to seamlessly release and deploy software on a large scale across hybrid environments, all while ensuring that compliance and security requirements are effectively in place.
      
      ## About this Operator
      
      Digital.ai Releas operator is based on helm chart that is available from [here](https://github.com/digital-ai/release-helm-chart).
      The operator includes subcharts which are dependencies for the Release containers to run successfully.
      Nginx Ingress and Haproxy ingress are disabled and not used with installations on the Openshift (and the images are not used in the installation)
      
      ### Subcharts include:
      
      - [PostgresSQL](https://github.com/bitnami/charts/tree/main/bitnami/postgresql)
      - [RabbitMQ](https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq)
      - [Nginx Ingress controller](https://github.com/bitnami/charts/tree/main/bitnami/nginx-ingress-controller)
      - [Haproxy Ingress controller](https://github.com/jcmoraisjr/haproxy-ingress/)
      
      ## Installation
        
      The installation can be done using the sample configuration provided below. Please note that this is a minimal configuration and it's not recommended for production use.
        
      ```
      apiVersion: xlr.digital.ai/v1alpha1
      kind: DigitalaiRelease
      metadata:
        name: dairelease-minimal
      spec:
        k8sSetup:
          platform: Openshift
        auth:
          adminPassword: 'admin'
        licenseAcceptEula: true
        keystore:
          passphrase: 'test1234'
          keystore: 'zs7OzgAAAAIAAAABAAAAAwAWZGVwbG95aXQtcGFzc3N3b3JkLWtleQAAAY66Cf9nrO0ABXNyADNjb20uc3VuLmNyeXB0by5wcm92aWRlci5TZWFsZWRPYmplY3RGb3JLZXlQcm90ZWN0b3LNV8pZ5zC7UwIAAHhyABlqYXZheC5jcnlwdG8uU2VhbGVkT2JqZWN0PjY9psO3VHACAARbAA1lbmNvZGVkUGFyYW1zdAACW0JbABBlbmNyeXB0ZWRDb250ZW50cQB+AAJMAAlwYXJhbXNBbGd0ABJMamF2YS9sYW5nL1N0cmluZztMAAdzZWFsQWxncQB+AAN4cHVyAAJbQqzzF/gGCFTgAgAAeHAAAAARMA8ECD0yEJAHFhBOAgMDDUB1cQB+AAUAAACQUhNP1jw1dwOxWArpm0JBAX40fr4fvvAmyGGrx7mzlCVjb4uOxi4IroUoxcbBx8cpjiS6QzCUg6chsCQ0IABB6s7Tow2VR8vRlxXyxpJXvlUwfH8hwJn/ZK8rQuDsCkzd2rC+lYR0pEO0lUP3/AQ7dHJ4TgloyZOKKbWRNJvE4K4EOafqASuNTkyrr0SPflRydAAWUEJFV2l0aE1ENUFuZFRyaXBsZURFU3QAFlBCRVdpdGhNRDVBbmRUcmlwbGVERVO3iVKkgrEJQ78wacyjhp3UZBSB/Q=='
        replicaCount: 1
        hooks:
          getLicense:
            enabled: true
        persistence:
          storageClass: ''
          accessModes:
            - ReadWriteOnce
          size: 1Gi
        postgresql:
          install: true
          primary:
            persistence:
              size: 1Gi
              storageClass: ''
        rabbitmq:
          install: true
          persistence:
            size: 1Gi
            size: 1Gi
            storageClass: ''
          replicaCount: 1
      ```
      
      ### Configuration Details
      
      The sample configuration uses:
      
        - Autogenerated limited license
        - Simple administrator initial password
        - Default keystore setup
        - Only one replica is set for all pods
        - All Pods are missing resource limit setup
        - Default storage class and minimal size for persistent storage
        - Release pods are using persistence access mode `ReadWriteOnce`, for Release pods the requirement is to have `ReadWriteMany`
        - Embedded PostgreSQL for DB management
        - Embedded RabbitMQ for message queue management
      
      ## Customize Your Configuration
      
      Configurations can be further personalized. Here are some areas you might want to consider:
      
        - **External DB:** For avoiding uncertified container images required by the subcharts, refer to these [instructions for setting up an external DB](https://docs.digital.ai/bundle/devops-release-version-v.23.3/page/release/operator/xl-op-release-external-db-migration.html).
        - **External Message Queue:** To set up an external message queue, follow this [guide](https://docs.digital.ai/bundle/devops-release-version-v.23.3/page/release/operator/xl-op-release-external-mq-migration.html).
        - **Custom License:** To apply a custom license, refer to this [process](https://docs.digital.ai/bundle/devops-release-version-v.23.3/page/release/operator/xl-op-release-license-update.html).
        - **Custom Configuration:** For modifying the configuration files, use this [guide](https://docs.digital.ai/bundle/devops-release-version-v.23.3/page/release/operator/xl-op-release-customize.html).
        - **Truststore Setup:** For modifying default truststore for Release, use this [guide](https://docs.digital.ai/bundle/devops-release-version-v.23.3/page/release/operator/xl-op-release-setup-truststore.html).
        - **Plugin Management:** Managing plugins can be done using the following methods:
                     - [Plugin Management using XL CLI](https://docs.digital.ai/bundle/devops-release-version-v.23.3/page/release/operator/xl-op-release-plugin-management.html)
                     - [Managing Plugins Offline for Kubernetes Environment](https://docs.digital.ai/bundle/devops-release-version-v.23.3/page/release/operator/xl-op-release-offline-plugin-management.html)


  displayName: Digital.ai Release
  icon:
    - base64data: "/9j/4AAQSkZJRgABAQEASABIAAD/2wCEAAYEBAUEBAYFBQUGBgYHCQ4JCQgICRINDQoOFRIWFhUSFBQXGiEcFxgfGRQUHScdHyIjJSUlFhwpLCgkKyEkJSQBBgYGCQgJEQkJESQYFBgkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJP/CABEIAMAAwAMBEQACEQEDEQH/xAA1AAEAAgIDAQEAAAAAAAAAAAAABwgFBgIDBAkBAQEAAwEBAQAAAAAAAAAAAAAAAgMEBQEG/9oADAMBAAIQAxAAAAC1AAAAAAAAAAAAAAAAAAAABhj2nsAAAAAAAAAAICKxGTLum1AAAAAAAAAApURwC2pM4AAAAAAAAAKUkcgtsTMAAAAAAAAAClJHILbEzAAAAAAAAAApSRyC2xMwAAAAAOkiAiU1E6jZyWCaymJHILbEzAAAAAGiFSzUgAAbodRqALbEzAAAAAjUpweQAAAAAtsTMAAAAYEoqYsAkIk45kdEZnEAFtiZgAAACqBCQO0tcTQa9TDpj5st9kaeqgHgALbEzAAAA8J8+zygsYWGj5XTjYdIy1DYrp2R7W+MrZVJALbEzAAAAjYpYDsPoERfzMsM83KAN+13WL7W6gJhAW2JmAAABDZUcGcPoAVt4mHRctIAyE5W8+i6VJiPAW2JmAAABFJTkHrPoSQlyckUYMwA23RbZ/u76GGrAtsTMAAADAFBDiC3JJ1cax8LBhK4D1e+2S7e7x6baQH4C2xMwAAABSsjcGZLqGyx80HJT0R83rXdwslSo1AAtsTMAAAAR8UnOAPcTySed5H5X8wQALbEzAAAAAr0VoAAAAABbYmYAAAAAgUrKecAAGTNyI6BbomIAAAAAGqlfCJzEAzRLxYY6iqB2FujKAAAAAAA4mHBmDkAAAAAAAAAAAAAAAAD/8QALRAAAQQCAQMDAwMFAQAAAAAABAIDBQYBBwgQETcAEjATFCAVIUAWIjEyUEH/2gAIAQEAAQwA/wCTIXOtRT+Rz5+KFejZiNmGfrRsgKa1/F5I7bPr7jdSgiFDErWtxeVrUpSq3aZipSTclDHPCEaxu7WwKeHOJRht7+JyHVlW2pvvnOevFFOMa7Lz3z/F5C+WpvrxS8clfxeQvlqb68UvHJX8XkL5am+vFLxyV8pZo0eO4SYQ0OxcOUFUgluDQrL02RO8n71KKVgFYUU0Xt6/Gqyp62S3pja16GV7m7ZM4zCckdgxK0/XkWJJumcqYGVWgayAuRD0fIhyojZgJLJQ/IXy1N9eKXjkr5Nnbfg9bB9iVfdyd72hZdgmKdljVYG/LW+1p7XEglwF9T4G17QDcrwdOx3vwP04peOSvj3Pt8XW8T9uJ9MiblZY6ckH5GRJcKL+Pil45K+K8W8Gj1oycPVj2WeySFtnC5mUey6T0xjv+2PVN0Rdbk2gliPwAHHcQk/TxmRtSvedxCY+nn7G1uYXbuO94qzayGw25YVaFNrUhaVJV+HFLxyV8XKC9qmrO3WRXc/Z9BRXzSWhhmlvP6c4/R9WHYmbKw0bM/shP/mMSWwqtEuZbLmxEuBbPp5zmG2pwZKmXmiG8OMuIcb2ro2Fv4zpobbUfNzsFIVuVIipQZYxfXil45K+GdlWoOFPlH84w3KyL8vJlyJS8rf6cXdatupcu0kzhWZOSFiAHzzXUtD3vacrbCHBxnXA4zpUb3M08pLgRClj1O0g26IbkQVdsckdaN2WtrsgLOP1PrxS8clfDyHlFRmqZb2K9qug7CyX22G8d11KBZrNajIZhOEo3/ZHEqCr7K84R+GmLK5C2xoFa8/avsoIZcZdThbd2gv6at0xD/v7enFLxyV8PKpak63YTj/HSiNIeusC25/p63Utar+ZhX+Pwrq1tz8atvv7/XIFCEbZnvZ268UvHJXw8mQFGasKdTjvnpEHKjJUM5H+0eY1IgjmMKwtrf8ABOMTAUyhOctfhquCXOXQBGE5y1nPbHf1tKaRYNhT8i2rCm+nFLxyV8N+gf6mpc1EYx3WtCm1qQvGUq6caL+3YqjivlPY/ULPXA7TDERZuP7LVUJSoyChJBnOE9IuKNmTWwo8ZwgjW1CapMTlLuUuSG6b41RKQYQh3GJDOcqznOc989OKXjkr4t+UpVP2AYppr2g9Kja5Olzw01FO/TI1vs2F2PEJLj3cNlyUUDLiqFkBWSmJLQ9YMcU4K6aD6D0BXmXMKJOPJTA1aGrTH0YoBkbFrtsRTIh6VmSkjj7P2PIbIsS5IrGWRevFLxyV8W69cJ2HUXGB0J/VH2HBnnGXkKbd6Q03JV6QakYox4MqmcsH2G2xrbFfceo3kJrmRbwrM/gVRm+dcht5XmzDu+rZyxjB2ls1eJeLet12nrvI5PnD3CXPw4peOSvj5C6UWfl64VwbKiM47ftn5OKXjkr484747Z9bj46NTa356oNtsHHx5cWW6GcM6MT+VcrUta5RqLhgnSytsahI1kFCOOkZKX04rMONa2dcWnOE/Jd9Y1i/j/TmgEqfuPFixxSnH64UzLjTNRsFedy3LQx4Su3rtn1B0qyWRxLcRCHmeqVxUmT1oItJzcaPUKNAUcDAUFHtjIv1HjdgVx+FksZTiz8fL5Xi3G2IlcqNT+PV2shzaDo12HCq9cBqcCHCRqMoG+ZxpDqcocQlaS6TVzlZUVXYh5QdKrEerChK9EsKQ2htOEoSlKf+F//EAD8QAAIBAQMHCAgFAgcAAAAAAAECAxEABCEQEjFBUWFxFSAiMIGRobIFEyMyQEKxwRRQcoKzUmJDU5KTwtHx/9oACAEBAA0/APykaY5r0isOwm39d3lVwO0H4aaIS3y8Rmjoh0Ip1E0qTspZjUsxqSbRkGqHouNjDQRuNnBjvEY0JKuDAbtY3H4UepA/2lyn0jJ5E+F9l/EuXlGTyJ8L7L+JcvKMnkT4X2X8S5eUZPInWxjOeSVwqqN5Nlwz4z6uEH9RxPYO2x0CCEOw/c9fpY6kmKDuWlv7ryzfU2GlL3Cpr+5aGzYevjJkhrv+ZfG0ozklicMrDcRb2X8S5eUZPInWSLWG5Rt0j/cx+Vd/dYNWK5xHNhj7NZ3nHnuwM9xkb2cg1kf0tvFr2sTBXFGUiNQQeBBGXlGTyJ1d6U/h4TiIx/mNu2DWbXhi8kshqWPWcoyeROqu69COtDLIfdQcTa8uWOxRqUbABgOY+IvF9JjDDaFpnHutrW73XAdpb7W1Ce6Cng1kxMlxJZgNpQgN3VspoVYUIPN5Rk8idV6KGdMAcHnYY1/SCBxJyysEjjQVZmJoABZgHSFxnR3XYKaGbfq1bbDwsuBRGzyOxa2OAEtY/FgLMKhlNQRxsBVLyi0WY7JANPHSLXZs142+o2g6QeZyjJ5E6m53d52rsVSfta9StNIx1sxJP1yqzQ3BWGgjBpPsO20Cl3c6hYEhYUNDINrnXw0ZSfaXaQ1jccNR3ix6MkZ96J9am3otM6TNGM0HzA7SukdvM5Rk8idTejHdhwZxXwByyOEUbSTQWud3SLDWQMT2mp7bMv4icDXiQo8Ce7m+kfYutcA/ynvw7bSKVZToIOBFrpepI0/TnHN8KZeUZPInUt6QiB/0ucrekLuDw9YMixRBeGb/AO80XqIrTbnjIXjJ4+rWuXlGTyJ1N1vMMx4Z2b/yy3aeOYftYH7WvEayow1hhUfW14i9S7bHUmneD4c26v8AiZTqAXEd5oMkl8dUI1qpzR4KMvKMnkTqb1dJFj/XSq+IFlJBB1HL6IGYqscZICeiRw93utKOi4GMbDQw4WqfVTAdCVdoP2yyGiogr2nYN9rxRrxINA2KNwte1N2ui1xz2GLftFT3WOJOXlGTyJ1XpIm93cgYDOPTXsavYRlgbQfdkXWrDWDaMD8Rc3I9ZC33XYbNpSRaix+WNwyjsYE+Nh8tVQHuFbH3mAqzcWOJtGMBXpSNqVRrJtFWO63atRElfFjpJ5nKMnkTqrlWe5sdbUxSuxh40tGxV0YUKkYEEZYjVZYmoeG8brCgN7uVFY7yhw7iOFj8l5hdCPAjxsPlhjkcnuWxwF4vns4xvzQanwsPcTRHENiroHN5Rk8idWBnX66xrjIB/iKNu0a9O3reUZPInWNV57j7qTnWU1K27Qd1omzXilUqyneDz5TgqDBRtY6AN5tfYnF4kUdBJga5q7qEadNDll9ISshOsZqD6g9aool6i6EycG1jcaiwxETkRTAdvRPeOFhhWWFgOw0ocp+aOE5o4toHfbAm73ciSZtxPur42PvyaZJTtZjibP04plHShkGhh/1rBsD0LxcqPnDevvA9ls4etvF7GawXXmppJ8LXSMItdLHWx3k1J49edIYVBsdJe6RknwsNBS6RgjwsNAUUH5H/AP/EACURAAIBAwMDBQEAAAAAAAAAAAECAwAEESExQBASIDIzQWFwgP/aAAgBAgEBPwD+E2uI13NLdRHY0CDtxGYKMmp7ppDgaDrDO0R0qGUSL3Dh38myDxspOyTHweHee6fGP1Dh38eGD+NqnfIPrhyxiRSpqWJozhuqqWOFq2gES678RkDDBFNYxnbShYINzUcSoMKPxv8A/8QAJBEAAgAFBAEFAAAAAAAAAAAAAQIAAxExQAQQICESMkFCcID/2gAIAQMBAT8A/CZmKLmBNQ+8DvEJAFTEyaWtbdJhW0I4YVGHqG+PGQ1Gphz/AF8VuMPUL3XjJWrYbKGFDDoVNDuASaCJUvwGIQD0YOnUwNOsKgW303//2Q=="
      mediatype: "image/jpg"
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: true
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - digitalai-release-operator
    - digitalai
    - digital.ai
    - release
    - devops
  links:
    - name: Digital.ai Release
      url: https://digital.ai/products/release/
    - name: Digital.ai Release Documentation
      url: https://docs.digital.ai/bundle/devops-release-version-v.24.1/page/release/operator/xl-op-before-you-begin.html
    - name: Digital.ai Release Helm Chart
      url: https://github.com/digital-ai/release-helm-chart
  maintainers:
    - email: support@digital.ai
      name: support
  maturity: alpha
  provider:
    name: Digital.ai
    url: https://digital.ai
  version: ${VERSION}
