{{- if and .Values.persistence.single .Values.persistence.enabled (not .Values.persistence.existingClaim)  -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "release.name" . }}
  labels: {{- include "common.labels.matchLabels" . | nindent 10 }}
  {{- if .Values.persistence.annotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.persistence.annotations "context" $) | nindent 10 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
      - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{ include "common.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) }}
  {{- if .Values.persistence.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.selector "context" $) | nindent 10 }}
  {{- end -}}
{{- end -}}
