apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  releasePassword:  {{ include "release.secretPassword" . | b64enc | quote }}
  {{- if .Values.license }}
  releaseLicense: {{ .Values.license | trim | b64enc | quote }}
  {{- end }}
  {{- if .Values.keystore.keystore }}
  repositoryKeystore: {{ .Values.keystore.keystore | b64enc | quote }}
  {{- end }}
  {{- if .Values.keystore.passphrase }}
  keystorePassphrase: {{ .Values.keystore.passphrase | b64enc | quote }}
  {{- end }}
  {{- if or .Values.external.db.enabled .Values.postgresql.install }}
  mainDatabaseUsername: {{ include "release.mainUsername" . | b64enc | quote }}
  mainDatabasePassword: {{ include "release.mainPassword" . | b64enc | quote }}
  reportDatabaseUsername: {{ include "release.reportUsername" . | b64enc | quote }}
  reportDatabasePassword: {{ include "release.reportPassword" . | b64enc | quote }}
  {{- end }}
  {{- if or .Values.external.mq.enabled .Values.rabbitmq.install }}
  rabbitmqUsername: {{ include "release.mqUsername" . | b64enc | quote }}
  rabbitmqPassword: {{ include "release.mqPassword" . | b64enc | quote }}
  {{- end }}
{{- range $key, $value := .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ ternary (printf "%s-%s" (include "common.names.namespace" $) $key) $key $.Values.extraSecretsPrependReleaseName }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData: {{- include "common.tplvalues.render" (dict "value" $value "context" $) | nindent 2 }}
{{- end }}
