apiVersion: v1
kind: Service
metadata:
  name: {{ template "xl-release.fullname" . }}
  labels:
    app: {{ template "xl-release.name" . }}
    chart: {{ template "xl-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "xl-release.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    {{- if .Values.http2.enabled }}
    - name: xlr-http2
      port: 443
      targetPort: http2
      protocol: TCP
    {{- else }}
    - name: xlr-http
      port: 80
      targetPort: http
      protocol: TCP
    {{- end }}
