apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELATED_IMAGE_GET_LICENSE
              value: docker.io/bitnami/kubectl:1.28.7-debian-12-r3
            - name: RELATED_IMAGE_GEN_SELF_SIGNED
              value: docker.io/bitnami/kubectl:1.28.7-debian-12-r3
            - name: RELATED_IMAGE_INSTALL_RELEASE_RUNNER
              value: docker.io/xebialabsunsupported/xl-client:${APP_VERSION}
            - name: RELATED_IMAGE_RELEASE
              value: docker.io/xebialabsunsupported/xl-release:${APP_VERSION}
            - name: RELATED_IMAGE_RELEASE_VOLUME_PERMISSIONS
              value: docker.io/bitnami/os-shell:12-debian-12-r16
            - name: RELATED_IMAGE_RELEASE_BUSY_BOX
              value: docker.io/library/busybox:stable
            - name: RELATED_IMAGE_POSTGRESQL
              value: docker.io/bitnami/postgresql:15.6.0-debian-12-r7
            - name: RELATED_IMAGE_POSTGRESQL_VOLUME_PERMISSIONS
              value: docker.io/bitnami/os-shell:12-debian-12-r16
            - name: RELATED_IMAGE_RABBITMQ
              value: docker.io/bitnami/rabbitmq:3.12.13-debian-12-r2
            - name: RELATED_IMAGE_RABBITMQ_VOLUME_PERMISSIONS
              value: docker.io/bitnami/os-shell:12-debian-12-r16
