
LABEL name="Digital.ai Release Operator" \
      vendor="Digital.ai" \
      version="${VERSION}" \
      release="1" \
      summary="Digital.ai Release Operator based on helm chart" \
      description="Digital.ai Release Operator based on helm chart from https://github.com/digital-ai/release-helm-chart"

COPY licenses /licenses
